/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 15 "concrete_return.c"
void __globinit_concrete_return(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 202 "../bin/../include/crest.h"
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 15 "concrete_return.c"
int main(void) 
{ 
  int x ;
  int __retres2 ;

  {
  __globinit_concrete_return();
  __CrestCall(1, 1);
#line 17
  __CrestInt(& x);
#line 18
  x = printf((char const   * __restrict  )"Hello.\n");
  __CrestHandleReturn(3, (long long )x);
  __CrestStore(2, (unsigned long )(& x));
  __CrestLoad(6, (unsigned long )(& x), (long long )x);
  __CrestLoad(5, (unsigned long )0, (long long )3);
  __CrestApply2(4, 12, (long long )(x == 3));
#line 19
  if (x == 3) {
    __CrestBranch(7, 3, 1);
    __CrestLoad(9, (unsigned long )0, (long long )1);
    __CrestStore(10, (unsigned long )(& __retres2));
#line 20
    __retres2 = 1;
#line 20
    goto return_label;
  } else {
    __CrestBranch(8, 5, 0);

  }
  __CrestLoad(11, (unsigned long )0, (long long )0);
  __CrestStore(12, (unsigned long )(& __retres2));
#line 21
  __retres2 = 0;
  return_label: /* CIL Label */ 
  {
  __CrestLoad(13, (unsigned long )(& __retres2), (long long )__retres2);
  __CrestReturn(14);
#line 15
  return (__retres2);
  }
}
}
void __globinit_concrete_return(void) 
{ 


  {
  __CrestInit();
}
}
