/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 3 "loop.c"
void __globinit_loop(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 202 "../bin/../include/crest.h"
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 3 "loop.c"
int main(void) 
{ 
  int num ;
  int __retres2 ;

  {
  __globinit_loop();
  __CrestCall(1, 1);
#line 6
  __CrestInt(& num);
  __CrestLoad(4, (unsigned long )(& num), (long long )num);
  __CrestLoad(3, (unsigned long )0, (long long )20);
  __CrestApply2(2, 16, (long long )(num < 20));
  if (num < 20) {
    __CrestBranch(5, 4, 1);
    printf((char const   * __restrict  )"Do nothing");
    __CrestClearStack(7);
    __CrestLoad(10, (unsigned long )(& num), (long long )num);
    __CrestLoad(9, (unsigned long )0, (long long )1);
    __CrestApply2(8, 0, (long long )(num + 1));
    __CrestStore(11, (unsigned long )(& num));
    num ++;
  } else {
    __CrestBranch(6, 5, 0);

  }
  __CrestLoad(14, (unsigned long )(& num), (long long )num);
  __CrestLoad(13, (unsigned long )0, (long long )20);
  __CrestApply2(12, 16, (long long )(num < 20));
  if (num < 20) {
    __CrestBranch(15, 7, 1);
    printf((char const   * __restrict  )"Do nothing");
    __CrestClearStack(17);
    __CrestLoad(20, (unsigned long )(& num), (long long )num);
    __CrestLoad(19, (unsigned long )0, (long long )1);
    __CrestApply2(18, 0, (long long )(num + 1));
    __CrestStore(21, (unsigned long )(& num));
    num ++;
  } else {
    __CrestBranch(16, 8, 0);

  }
  __CrestLoad(22, (unsigned long )0, (long long )0);
  __CrestStore(23, (unsigned long )(& __retres2));
#line 11
  __retres2 = 0;
  __CrestLoad(24, (unsigned long )(& __retres2), (long long )__retres2);
  __CrestReturn(25);
#line 3
  return (__retres2);
}
}
void __globinit_loop(void) 
{ 


  {
  __CrestInit();
}
}
