/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 26 "structure_test.c"
void __globinit_structure_test(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 15 "structure_test.c"
struct bar {
   int x ;
   int y ;
};
#line 20 "structure_test.c"
struct foo {
   int x ;
   struct bar bar ;
   int y ;
};
#line 202 "../bin/../include/crest.h"
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 26 "structure_test.c"
int main(void) 
{ 
  struct foo f1 ;
  struct foo f2 ;
  struct bar b ;
  int __retres4 ;

  {
  __globinit_structure_test();
  __CrestCall(1, 1);
#line 30
  __CrestInt(& b.x);
#line 31
  __CrestInt(& b.y);
  __CrestLoad(2, (unsigned long )0, (long long )7);
  __CrestStore(3, (unsigned long )(& f1.x));
#line 33
  f1.x = 7;
#line 34
  f1.bar = b;
  __CrestLoad(4, (unsigned long )0, (long long )19);
  __CrestStore(5, (unsigned long )(& f1.y));
#line 35
  f1.y = 19;
#line 37
  __CrestInt(& f2.x);
#line 38
  __CrestInt(& f2.y);
#line 40
  f2 = f1;
  __CrestLoad(6, (unsigned long )0, (long long )0);
  __CrestStore(7, (unsigned long )(& __retres4));
#line 47
  __retres4 = 0;
  __CrestLoad(8, (unsigned long )(& __retres4), (long long )__retres4);
  __CrestReturn(9);
#line 26
  return (__retres4);
}
}
void __globinit_structure_test(void) 
{ 


  {
  __CrestInit();
}
}
