/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 12 "sixtimes.c"
void __globinit_sixtimes(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 202 "../bin/../include/crest.h"
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 3 "sixtimes.c"
int inc(int x ) 
{ 


  {
  __CrestCall(2, 1);
  __CrestStore(1, (unsigned long )(& x));
  __CrestLoad(5, (unsigned long )(& x), (long long )x);
  __CrestLoad(4, (unsigned long )0, (long long )1);
  __CrestApply2(3, 0, (long long )(x + 1));
  __CrestStore(6, (unsigned long )(& x));
#line 4
  x ++;
  {
  __CrestLoad(7, (unsigned long )(& x), (long long )x);
  __CrestReturn(8);
#line 5
  return (x);
  }
}
}
#line 7 "sixtimes.c"
int mult(int y ) 
{ 


  {
  __CrestCall(10, 2);
  __CrestStore(9, (unsigned long )(& y));
  __CrestLoad(13, (unsigned long )0, (long long )6);
  __CrestLoad(12, (unsigned long )(& y), (long long )y);
  __CrestApply2(11, 2, (long long )(6 * y));
  __CrestStore(14, (unsigned long )(& y));
#line 8
  y = 6 * y;
  __CrestLoad(15, (unsigned long )(& y), (long long )y);
#line 9
  y = inc(y);
  __CrestHandleReturn(17, (long long )y);
  __CrestStore(16, (unsigned long )(& y));
  {
  __CrestLoad(18, (unsigned long )(& y), (long long )y);
  __CrestReturn(19);
#line 10
  return (y);
  }
}
}
#line 12 "sixtimes.c"
int main(void) 
{ 
  int a ;
  int b ;
  int __retres3 ;

  {
  __globinit_sixtimes();
  __CrestCall(20, 3);
#line 14
  __CrestInt(& a);
  __CrestLoad(21, (unsigned long )(& a), (long long )a);
#line 15
  a = mult(a);
  __CrestHandleReturn(23, (long long )a);
  __CrestStore(22, (unsigned long )(& a));
  __CrestLoad(26, (unsigned long )(& a), (long long )a);
  __CrestLoad(25, (unsigned long )0, (long long )31);
  __CrestApply2(24, 12, (long long )(a == 31));
#line 16
  if (a == 31) {
    __CrestBranch(27, 7, 1);
    __CrestLoad(29, (unsigned long )0, (long long )1);
    __CrestStore(30, (unsigned long )(& b));
#line 17
    b = 1;
  } else {
    __CrestBranch(28, 8, 0);
    __CrestLoad(31, (unsigned long )0, (long long )2);
    __CrestStore(32, (unsigned long )(& b));
#line 19
    b = 2;
  }
  __CrestLoad(33, (unsigned long )0, (long long )0);
  __CrestStore(34, (unsigned long )(& __retres3));
#line 20
  __retres3 = 0;
  __CrestLoad(35, (unsigned long )(& __retres3), (long long )__retres3);
  __CrestReturn(36);
#line 12
  return (__retres3);
}
}
void __globinit_sixtimes(void) 
{ 


  {
  __CrestInit();
}
}
